#!/usr/bin/env bash
# personalized configuration of nginx
./configure --prefix=/opt/nginx \
--without-http_scgi_module \
--without-http_uwsgi_module \
--without-http_fastcgi_module \
--without-http_autoindex_module \
--without-http_ssi_module \
--add-module=/opt/headers-more-nginx-module \
--with-http_dav_module \
--with-ipv6 \
--with-http_ssl_module \
--with-http_realip_module \
--with-http_addition_module \
--with-http_xslt_module \
--with-http_sub_module \
--with-http_flv_module \
--with-http_mp4_module \
--with-http_gunzip_module \
--with-http_gzip_static_module \
--with-http_random_index_module \
--with-http_secure_link_module \
--with-http_degradation_module \
--with-http_stub_status_module

mkdir logs

make
